let supabaseClient,session=null,products=[],categories=[];
document.addEventListener("DOMContentLoaded",init);
async function init(){bindEvents();try{supabaseClient=getSupabaseClient();const res=await supabaseClient.auth.getSession();session=res.data.session;updateLoginState()}catch(err){showWarning(err.message)}}
function showWarning(msg){const box=document.getElementById("config-warning");box.textContent=msg;box.classList.remove("hidden")}
function bindEvents(){document.getElementById("login-btn").addEventListener("click",login);document.getElementById("logout-btn").addEventListener("click",logout);document.getElementById("save-product-btn").addEventListener("click",saveProduct);document.getElementById("reset-form-btn").addEventListener("click",resetForm);document.getElementById("reload-btn").addEventListener("click",loadAll);document.getElementById("search").addEventListener("input",renderProducts);document.getElementById("csv-template-btn").addEventListener("click",downloadTemplate);document.getElementById("csv-export-btn").addEventListener("click",exportCsv);document.getElementById("csv-import").addEventListener("change",importCsv);document.getElementById("add-category-btn").addEventListener("click",addCategory)}
async function login(){const email=document.getElementById("login-email").value.trim(),password=document.getElementById("login-password").value,status=document.getElementById("login-status");status.textContent="Login läuft...";const{data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){status.textContent=error.message;return}session=data.session;status.textContent="";updateLoginState()}
async function logout(){await supabaseClient.auth.signOut();session=null;updateLoginState()}
async function updateLoginState(){if(session){document.getElementById("login-card").classList.add("hidden");document.getElementById("admin-area").classList.remove("hidden");document.getElementById("logout-btn").classList.remove("hidden");await loadAll()}else{document.getElementById("login-card").classList.remove("hidden");document.getElementById("admin-area").classList.add("hidden");document.getElementById("logout-btn").classList.add("hidden")}}
async function loadAll(){await loadProducts();buildCategories();renderCategorySelect();renderCategoryList();renderProducts()}
async function loadProducts(){const{data,error}=await supabaseClient.from("products").select("*").order("id",{ascending:true});if(error){alert(error.message);return}products=(data||[]).map(productFromRow)}
function buildCategories(){categories=[...new Set(products.map(p=>p.category).filter(Boolean))].sort()}
function renderCategorySelect(){const sel=document.getElementById("p-category");const current=sel.value;sel.innerHTML='<option value="">Kategorie wählen...</option>';categories.forEach(c=>{const opt=document.createElement("option");opt.value=c;opt.textContent=c;sel.appendChild(opt)});sel.value=categories.includes(current)?current:""}
function renderCategoryList(){const list=document.getElementById("category-list");list.innerHTML="";if(!categories.length){list.innerHTML='<div class="sub">Noch keine Kategorien.</div>';return}categories.forEach(c=>{const chip=document.createElement("span");chip.className="category-chip";chip.innerHTML="<span></span><button type='button'>×</button>";chip.querySelector("span").textContent=c;chip.querySelector("button").addEventListener("click",()=>removeCategory(c));list.appendChild(chip)})}
function addCategory(){const input=document.getElementById("new-category");const val=input.value.trim();if(!val)return;if(!categories.includes(val))categories.push(val);categories.sort();input.value="";renderCategorySelect();document.getElementById("p-category").value=val;renderCategoryList()}
async function removeCategory(cat){if(products.some(p=>p.category===cat)){alert("Diese Kategorie wird noch von Produkten verwendet. Bitte Produkte vorher ändern.");return}categories=categories.filter(c=>c!==cat);renderCategorySelect();renderCategoryList()}
function renderProducts(){const list=document.getElementById("product-list"),q=document.getElementById("search").value.toLowerCase();list.innerHTML="";const filtered=products.filter(p=>!q||[p.title,p.desc,p.category].join(" ").toLowerCase().includes(q));if(!filtered.length){list.innerHTML='<div class="notice">Keine Produkte gefunden.</div>';return}filtered.forEach(p=>{const row=document.createElement("div");row.className="product-admin-item";row.innerHTML='<img src="'+(p.imgFront||"")+'" alt=""><div><strong></strong><div class="sub"></div><div class="product-actions"></div></div>';row.querySelector("strong").textContent=p.title;row.querySelector(".sub").textContent="€ "+formatPrice(p.price)+" · Druck € "+formatPrice(p.printPrice||0)+" · Min. "+(p.minQty||1)+" · "+(p.category||"Ohne Kategorie")+" · "+(p.active?"aktiv":"inaktiv");const actions=row.querySelector(".product-actions");actions.appendChild(actionBtn("Bearbeiten","edit-btn",()=>editProduct(p)));actions.appendChild(actionBtn("Duplizieren","copy-btn",()=>duplicateProduct(p)));actions.appendChild(actionBtn("Löschen","delete-btn",()=>deleteProduct(p.id)));list.appendChild(row)})}
function actionBtn(text,cls,fn){const b=document.createElement("button");b.className=cls;b.type="button";b.textContent=text;b.addEventListener("click",fn);return b}
function editProduct(p){document.getElementById("form-title").textContent="Produkt bearbeiten";document.getElementById("edit-id").value=p.id;document.getElementById("p-title").value=p.title;document.getElementById("p-category").value=p.category;document.getElementById("p-desc").value=p.desc;document.getElementById("p-price").value=p.price;document.getElementById("p-print-price").value=p.printPrice ?? 5;document.getElementById("p-min-qty").value=p.minQty ?? 1;document.getElementById("p-discount-20").value=p.discount20 ?? 0;document.getElementById("p-discount-50").value=p.discount50 ?? 0;document.getElementById("p-sizes").value=(p.sizes||[]).join(",");document.getElementById("p-active").checked=p.active;window.scrollTo({top:0,behavior:"smooth"})}
function resetForm(){document.getElementById("form-title").textContent="Produkt anlegen";document.getElementById("edit-id").value="";["p-title","p-desc","p-price"].forEach(id=>document.getElementById(id).value="");document.getElementById("p-print-price").value="5.00";document.getElementById("p-min-qty").value="1";document.getElementById("p-discount-20").value="0";document.getElementById("p-discount-50").value="0";document.getElementById("p-category").value="";document.getElementById("p-sizes").value="S,M,L,XL,XXL";document.getElementById("p-front").value="";document.getElementById("p-back").value="";document.getElementById("p-left").value="";document.getElementById("p-right").value="";document.getElementById("p-active").checked=true}
async function uploadFile(file,prefix){if(!file)return"";const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const filename=prefix+"-"+Date.now()+"-"+Math.random().toString(16).slice(2)+"."+ext;const{error}=await supabaseClient.storage.from(window.PROTEX_CONFIG.STORAGE_BUCKET).upload(filename,file,{cacheControl:"3600",upsert:false});if(error)throw error;const{data}=supabaseClient.storage.from(window.PROTEX_CONFIG.STORAGE_BUCKET).getPublicUrl(filename);return data.publicUrl}
async function saveProduct(){const status=document.getElementById("save-status");status.textContent="Speichern...";try{const id=document.getElementById("edit-id").value,old=id?products.find(p=>String(p.id)===String(id)):null;const frontFile=document.getElementById("p-front").files[0],
      backFile=document.getElementById("p-back").files[0],
      leftFile=document.getElementById("p-left").files[0],
      rightFile=document.getElementById("p-right").files[0];

    let imgFront=old?.imgFront||"",
        imgBack=old?.imgBack||"",
        imgLeft=old?.imgLeft||"",
        imgRight=old?.imgRight||"";

    if(frontFile)imgFront=await uploadFile(frontFile,"front");
    if(backFile)imgBack=await uploadFile(backFile,"back");
    if(leftFile)imgLeft=await uploadFile(leftFile,"left");
    if(rightFile)imgRight=await uploadFile(rightFile,"right");
    if(!imgFront)throw new Error("Bitte ein Vorderseitenbild hochladen.");const product={title:document.getElementById("p-title").value.trim(),category:document.getElementById("p-category").value.trim(),desc:document.getElementById("p-desc").value.trim(),price:document.getElementById("p-price").value.trim(),printPrice:Number(document.getElementById("p-print-price").value.replace(",","."))||0,minQty:Number(document.getElementById("p-min-qty").value)||1,discount20:Number(document.getElementById("p-discount-20").value)||0,discount50:Number(document.getElementById("p-discount-50").value)||0,sizes:splitList(document.getElementById("p-sizes").value),imgFront,imgBack,imgLeft,imgRight,active:document.getElementById("p-active").checked};if(!product.title)throw new Error("Produktname fehlt.");const row=rowFromProduct(product);if(id){const{error}=await supabaseClient.from("products").update(row).eq("id",id);if(error)throw error}else{const{error}=await supabaseClient.from("products").insert(row);if(error)throw error}status.textContent="Gespeichert.";resetForm();await loadAll()}catch(err){status.textContent=err.message}}
async function duplicateProduct(p){const row=rowFromProduct({...p,title:p.title+" Kopie"});const{error}=await supabaseClient.from("products").insert(row);if(error)alert(error.message);await loadAll()}
async function deleteProduct(id){if(!confirm("Produkt wirklich löschen?"))return;const{error}=await supabaseClient.from("products").delete().eq("id",id);if(error)alert(error.message);await loadAll()}
function downloadTemplate(){const csv="Produktname,Beschreibung,Preis,Kategorie,Größen\\nT-Shirt Premium,100% Baumwolle,19.90,T-Shirt,S|M|L|XL|XXL\\n";downloadText(csv,"produkt-vorlage.csv","text/csv;charset=utf-8")}
function exportCsv(){const rows=[["Produktname","Beschreibung","Preis","Kategorie","Größen","Druckpreis","Mindestmenge","Rabatt20","Rabatt50","Aktiv"]];products.forEach(p=>rows.push([p.title,p.desc,p.price,p.category,(p.sizes||[]).join("|"),p.printPrice||0,p.minQty||1,p.discount20||0,p.discount50||0,p.active]));const csv=rows.map(row=>row.map(csvEscape).join(",")).join("\\n");downloadText(csv,"produkte-export.csv","text/csv;charset=utf-8")}
function csvEscape(value){const s=String(value??"");return/[",\\n;]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
function parseCsvLine(line){const out=[];let cur="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++}else if(ch==='"')quoted=!quoted;else if((ch===","||ch===";")&&!quoted){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out.map(v=>v.trim())}
async function importCsv(e){const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\\r?\\n/).filter(l=>l.trim());const rows=[];for(let i=1;i<lines.length;i++){const c=parseCsvLine(lines[i]);if(!c[0])continue;rows.push({name:c[0],description:c[1]||"",price:c[2]||"",category:c[3]||"",sizes:(c[4]||"").replaceAll("|",","),print_price_element:Number(c[5]||5)||5,min_qty:Number(c[6]||1)||1,discount_20:Number(c[7]||0)||0,discount_50:Number(c[8]||0)||0,active:true})}if(!rows.length){alert("Keine Produkte gefunden.");return}const{error}=await supabaseClient.from("products").insert(rows);if(error)alert(error.message);else alert(rows.length+" Produkte importiert. Bilder bitte ergänzen.");e.target.value="";await loadAll()}
function downloadText(text,filename,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
